#ifndef OPERATINGSYSTEMSASSIGNMENT3_TLBHANDLING_H
#define OPERATINGSYSTEMSASSIGNMENT3_TLBHANDLING_H


class tlbhandling {
    tlbhandling();
};


#endif //OPERATINGSYSTEMSASSIGNMENT3_TLBHANDLING_H
